# Generated by Django 4.2.13 on 2024-05-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormulasPresionManometrica',
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_B',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_residuales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='ca_i_x9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
