# Generated by Django 4.2.13 on 2024-05-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_delete_formulaspresionmanometrica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='deriva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
