# Generated by Django 4.2.13 on 2024-05-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_patronespresionmanometrica_deriva'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronespresionmanometrica',
            name='reproducibilidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
