# Generated by Django 4.2.13 on 2024-05-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_alter_presionmanometrica_ambientales_humedad_relativa_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_humedad_relativa_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_humedad_relativa_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_presion_barometrica_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_presion_barometrica_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_temperatura_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_temperatura_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
