# Generated by Django 4.2.13 on 2024-05-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_alter_presionmanometrica_ambientales_humedad_relativa_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal2_ciclo2_lectura_IBC_descenso',
        ),
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal2_ciclo2_lectura_patron_descenso',
        ),
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal6',
        ),
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal6_ciclo1_lectura_IBC_ascenso',
        ),
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal6_ciclo1_lectura_IBC_descenso',
        ),
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal6_ciclo1_lectura_patron_ascenso',
        ),
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal6_ciclo1_lectura_patron_descenso',
        ),
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal6_ciclo2_lectura_IBC_ascenso',
        ),
        migrations.RemoveField(
            model_name='presionmanometrica',
            name='valor_nominal6_ciclo2_lectura_patron_ascenso',
        ),
    ]
