# Generated by Django 4.2.13 on 2024-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_remove_presionmanometrica_valor_nominal2_ciclo2_lectura_ibc_descenso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_humedad_relativa_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_humedad_relativa_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_presion_barometrica_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_presion_barometrica_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_temperatura_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='ambientales_temperatura_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presionmanometrica',
            name='sitio_altura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
