# Generated by Django 4.2.13 on 2024-06-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0009_presiondiferencial_c_e_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronesPresionDiferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_identificacion', models.CharField(max_length=10)),
                ('patron_descripcion', models.CharField(max_length=100)),
                ('patron_intervalo_medida', models.CharField(max_length=100)),
                ('patron_modelo', models.CharField(max_length=50)),
                ('patron_no_serie', models.CharField(max_length=50)),
                ('patron_certificado', models.CharField(max_length=50)),
                ('patron_vigencia', models.DateField()),
                ('patron_trazabilidad', models.CharField(max_length=100)),
                ('patron_reproducibilidad', models.FloatField(blank=True, null=True)),
                ('ca_x10', models.FloatField(blank=True, null=True)),
                ('ca_x9', models.FloatField(blank=True, null=True)),
                ('ca_x8', models.FloatField(blank=True, null=True)),
                ('ca_x7', models.FloatField(blank=True, null=True)),
                ('ca_x6', models.FloatField(blank=True, null=True)),
                ('ca_x5', models.FloatField(blank=True, null=True)),
                ('ca_x4', models.FloatField(blank=True, null=True)),
                ('ca_x3', models.FloatField(blank=True, null=True)),
                ('ca_x2', models.FloatField(blank=True, null=True)),
                ('ca_x', models.FloatField(blank=True, null=True)),
                ('ca_B', models.FloatField(blank=True, null=True)),
                ('ca_residuales', models.FloatField(blank=True, null=True)),
                ('ca_i_x10', models.FloatField(blank=True, null=True)),
                ('ca_i_x9', models.FloatField(blank=True, null=True)),
                ('ca_i_x8', models.FloatField(blank=True, null=True)),
                ('ca_i_x7', models.FloatField(blank=True, null=True)),
                ('ca_i_x6', models.FloatField(blank=True, null=True)),
                ('ca_i_x5', models.FloatField(blank=True, null=True)),
                ('ca_i_x4', models.FloatField(blank=True, null=True)),
                ('ca_i_x3', models.FloatField(blank=True, null=True)),
                ('ca_i_x2', models.FloatField(blank=True, null=True)),
                ('ca_i_x', models.FloatField(blank=True, null=True)),
                ('ca_i_B', models.FloatField(blank=True, null=True)),
                ('ca_i_residuales', models.FloatField(blank=True, null=True)),
                ('deriva', models.FloatField(blank=True, null=True)),
                ('reproducibilidad', models.FloatField(blank=True, null=True)),
                ('patron_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrones_pd_marca', to='CRUD.patronesmarcas')),
            ],
        ),
    ]
