# Generated by Django 4.2.13 on 2024-06-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0010_patronespresiondiferencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presiondiferencial',
            name='unidades_toma_datos',
            field=models.CharField(blank=True, choices=[('kPa', 'kPa'), ('Lb*f/in2', 'Lb*f/in2'), ('kg*f/cm2', 'kg*f/cm2'), ('inH2O', 'inH2O')], max_length=20, null=True),
        ),
    ]
