# Generated by Django 4.2.13 on 2024-06-10 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0011_alter_presiondiferencial_unidades_toma_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperatura',
            name='archivos_asociado',
        ),
        migrations.AddField(
            model_name='temperatura',
            name='C_E',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ambientales_altura_IBC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ambientales_altura_patron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ambientales_humedad_relativa_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ambientales_humedad_relativa_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ambientales_presion_barometrica_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ambientales_presion_barometrica_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ambientales_temperatura_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ambientales_temperatura_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='cliente_correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='cliente_nombre_razon_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='coeficiente_termico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='desviacion_ciclo1_IBC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='desviacion_ciclo1_patron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='desviacion_ciclo2_IBC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='desviacion_ciclo2_patron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='fecha_calibracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='fecha_entrega_IBC',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_accesorios_incluidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_condicion_recepcion_del_IBC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_especificaciones_particulares_almacenaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_especificaciones_particulares_conservacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_especificaciones_particulares_manejo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_especificaciones_particulares_proteccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_especificaciones_particulares_transporte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_incertidumbre_requerida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_intervalo_de_medida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_otra_identificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='instrumento_resolucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='lugar_de_calibracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='magnitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='metodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='patron_id_presion_manometrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperatura_patron_set', to='CRUD.patronespresionmanometrica'),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='procedimiento_utilizado',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='sitio_altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='sitio_lat_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='sitio_lat_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='sitio_lat_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='solicitud_servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='temperatura_referencia_IBC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='unidades',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='unidades_toma_datos',
            field=models.CharField(blank=True, choices=[('°C', '°C'), ('°F', '°F'), ('K', 'K')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal1_ciclo1_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal1_ciclo1_lectura_IBC_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal1_ciclo1_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal1_ciclo1_lectura_patron_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal1_ciclo2_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal1_ciclo2_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal2_ciclo1_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal2_ciclo1_lectura_IBC_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal2_ciclo1_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal2_ciclo1_lectura_patron_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal2_ciclo2_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal2_ciclo2_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal3_ciclo1_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal3_ciclo1_lectura_IBC_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal3_ciclo1_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal3_ciclo1_lectura_patron_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal3_ciclo2_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal3_ciclo2_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal4_ciclo1_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal4_ciclo1_lectura_IBC_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal4_ciclo1_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal4_ciclo1_lectura_patron_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal4_ciclo2_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal4_ciclo2_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal5_ciclo1_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal5_ciclo1_lectura_IBC_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal5_ciclo1_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal5_ciclo1_lectura_patron_descenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal5_ciclo2_lectura_IBC_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatura',
            name='valor_nominal5_ciclo2_lectura_patron_ascenso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
